name: ecmwf-models
channels:
- conda-forge
dependencies:
- numpy
- pandas
- matplotlib
- libnetcdf
- xarray
- pygrib
- configobj
- basemap
- scipy
- pip:
    - pygeogrids
    - pygeobase
    - pyresample
    - configobj
    - ecmwf-api-client
    - pynetcf
    - repurpose
    - pytesmo
    - datedown>=0.3
    - netCDF4==1.2.3.1 # !! netcdf4-python
