name: ecmwf-models
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - bzip2=1.0.8
  - ca-certificates=2019.6.16
  - certifi=2019.6.16
  - cftime=1.0.3.4
  - configobj=5.0.6
  - curl=7.65.3
  - eccodes=2.13.0
  - hdf4=4.2.13
  - hdf5=1.10.5
  - jasper=1.900.1
  - jpeg=9c
  - krb5=1.16.3
  - libaec=1.0.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.65.3
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - liblapack=3.8.0
  - libnetcdf=4.6.2
  - libopenblas=0.3.6
  - libpng=1.6.37
  - libssh2=1.8.2
  - libstdcxx-ng=9.1.0
  - ncurses=6.1
  - netcdf4=1.5.1.2
  - numpy=1.17.0
  - openssl=1.1.1c
  - pandas=0.25.0
  - pip=19.2.1
  - proj4=6.1.0
  - pygrib=2.0.4
  - pykdtree=1.3.1
  - pyproj=2.2.1
  - pyresample=1.12.3
  - python=3.6.7
  - python-dateutil=2.8.0
  - pytz=2019.2
  - pyyaml=5.1.2
  - readline=8.0
  - scipy=1.3.0
  - setuptools=41.0.1
  - six=1.12.0
  - sqlite=3.29.0
  - tk=8.6.9
  - wheel=0.33.4
  - xarray=0.12.3
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - pip:
    - ascat==1.0
    - cdsapi==0.2.3
    - configparser==3.7.4
    - cycler==0.10.0
    - cython==0.29.13
    - datedown==0.3
    - ecmwf-api-client==1.5.4
    - ismn==0.3.1
    - kiwisolver==1.1.0
    - lxml==4.4.0
    - matplotlib==3.1.1
    - more-itertools==7.2.0
    - pygeobase==0.3.18
    - pygeogrids==0.2.5
    - pynetcf==0.1.19
    - pyparsing==2.4.2
    - pytesmo==0.7.0
    - repurpose==0.6
    - requests==2.22.0

