name: ecmwf-models
channels:
- conda-forge
dependencies:
- matplotlib
- pandas
- pygrib>=2.0.1
- netcdf4
- scipy
- pyresample
- xarray
- pip:
    - pygeobase
    - pynetcf
    - repurpose
    - pygeogrids
    - cdsapi
    - ecmwf-api-client
    - datedown>=0.3
    - more_itertools<=5.0
