name: ecmwf-models
channels:
  - conda-forge
dependencies:
- pygrib
- pip:
    - pygeobase
    - https://software.ecmwf.int/wiki/download/attachments/56664858/ecmwf-api-client-python.tgz#egg=ecmwf_api_client
