name: ecmwf-models
channels:
- conda-forge
dependencies:
- numpy
- netcdf4
- pandas
- configobj
- pygrib>=2.0.1
- scipy
- pyresample
- xarray
- pytest=3.1.2
- pip:
    - pygeogrids
    - pygeobase
    - configobj
    - ecmwf-api-client
    - pynetcf
    - repurpose
    - pytesmo
    - datedown>=0.3
    - coverage==4.1
    - pytest-cov==2.2.1
