name: ecmwf-models
channels:
- conda-forge
dependencies:
- numpy
- matplotlib
- netcdf4
- pandas
- configobj
- pygrib>=2.0.1
- scipy
- pyresample
- xarray
- pip:
    - pygeogrids
    - pygeobase
    - configobj
    - cdsapi
    - ecmwf-api-client
    - pynetcf
    - repurpose
    - datedown>=0.3
