name: ecmwf-models
channels:
- conda-forge
dependencies:
- numpy
- pandas
- configobj
- pygrib>=2.0.1
- hdf5
- netcdf4>=1.4.2
- scipy
- pyresample
- xarray
- pip
- pip:
    - pygeobase
    - pynetcf
    - repurpose
    - pygeogrids
    - cdsapi
    - ecmwf-api-client
    - datedown>=0.3
    - requests
    - more_itertools
