name: ecmwf_models
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.10.8
  - cdo=1.9.10
  - certifi=2021.10.8
  - cftime=1.5.0
  - configobj=5.0.6
  - curl=7.78.0
  - eccodes=2.22.1
  - expat=2.4.1
  - fftw=3.3.9
  - hdf4=4.2.15
  - hdf5=1.10.6
  - icu=58.2
  - jasper=1.900.1
  - jbig=2.1
  - jpeg=9d
  - krb5=1.19.2
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libaec=1.0.5
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.78.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=11.1.0
  - libgfortran5=11.1.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.17
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - libzip=1.8.0
  - lz4-c=1.9.3
  - ncurses=6.2
  - netcdf4=1.5.7
  - numpy=1.21.1
  - openssl=1.1.1k
  - ossuuid=1.6.2
  - pandas=1.3.1
  - pip=21.2.4
  - proj=8.0.1
  - pygrib=2.1.3
  - pykdtree=1.3.4
  - pyproj=3.1.0
  - pyresample=1.20.0
  - python=3.9.6
  - python-cdo=1.5.5
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.1
  - pyyaml=5.4.1
  - readline=8.1
  - scipy=1.7.0
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - tzdata=2021a
  - udunits2=2.2.27.27
  - wheel=0.37.0
  - xarray=0.19.0
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - attrs==21.2.0
    - cdsapi==0.5.1
    - charset-normalizer==2.0.4
    - coverage==6.1.2
    - datedown==0.3
    - ecmwf-api-client==1.6.1
    - idna==3.2
    - iniconfig==1.1.1
    - more-itertools==8.9.0
    - packaging==21.2
    - pluggy==1.0.0
    - py==1.11.0
    - pygeobase==0.4.0
    - pygeogrids==0.4.1
    - pynetcf==0.2.2
    - pyparsing==2.4.7
    - pytest==6.2.5
    - pytest-cov==3.0.0
    - repurpose==0.8
    - requests==2.26.0
    - toml==0.10.2
    - tomli==1.2.2
    - tqdm==4.62.2
    - urllib3==1.26.6
